// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: cache/v1alpha1/cache.proto

package cachev1alpha1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheBackendService_Ping_FullMethodName = "/cache.v1alpha1.CacheBackendService/Ping"
)

// CacheBackendServiceClient is the client API for CacheBackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheBackendServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type cacheBackendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheBackendServiceClient(cc grpc.ClientConnInterface) CacheBackendServiceClient {
	return &cacheBackendServiceClient{cc}
}

func (c *cacheBackendServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CacheBackendService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheBackendServiceServer is the server API for CacheBackendService service.
// All implementations must embed UnimplementedCacheBackendServiceServer
// for forward compatibility.
type CacheBackendServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedCacheBackendServiceServer()
}

// UnimplementedCacheBackendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheBackendServiceServer struct{}

func (UnimplementedCacheBackendServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCacheBackendServiceServer) mustEmbedUnimplementedCacheBackendServiceServer() {}
func (UnimplementedCacheBackendServiceServer) testEmbeddedByValue()                             {}

// UnsafeCacheBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheBackendServiceServer will
// result in compilation errors.
type UnsafeCacheBackendServiceServer interface {
	mustEmbedUnimplementedCacheBackendServiceServer()
}

func RegisterCacheBackendServiceServer(s grpc.ServiceRegistrar, srv CacheBackendServiceServer) {
	// If the following call pancis, it indicates UnimplementedCacheBackendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheBackendService_ServiceDesc, srv)
}

func _CacheBackendService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheBackendServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheBackendService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheBackendServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheBackendService_ServiceDesc is the grpc.ServiceDesc for CacheBackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheBackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.v1alpha1.CacheBackendService",
	HandlerType: (*CacheBackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CacheBackendService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache/v1alpha1/cache.proto",
}
