#!/usr/bin/env python3
"""Regenerate golden_vectors.json — the canonical, language-neutral golden
fixture for the content-fingerprint scheme.

The fixture pins the construction (XXH3-64, seed 1337) byte-for-byte across
every implementation that must agree on the same routing keys:

  * Go     — pkg/fingerprint (this repo; fingerprint_test.go loads the fixture)
  * Python — the inference-cache-benchmark dumb gateway client
             (lib/dumb_gateway_client.py; its test suite carries a copy of this
             file that must stay byte-identical)
  * Rust   — SMG's event_tree.rs (XXH3_SEED / compute_next_seq_hash)

Scheme (mirrors SMG's event_tree.rs):

    seed              = 1337
    content_hash(blk) = XXH3_64(seed) over concat(token.to_le_bytes() as u32)
    prefix_hash[0]    = content_hash[0]            (fresh sequence)
    prefix_hash[0]    = next(parent, content[0])   (when a parent prefix is given)
    prefix_hash[i]    = XXH3_64(seed) over prev.le8 ++ content_hash[i].le8
    wire form         = 8-byte big-endian (base64 of those bytes in the JSON)

Partial trailing tokens (fewer than block_size) are dropped — engines cache
only full blocks.

The scheme is FROZEN. Regenerating this file must be a no-op; if it is not,
every consumer above breaks and the change needs cross-repo coordination.

Run:  python3 gen_golden.py            (writes golden_vectors.json next to
      this script; deps: pip install -r requirements.txt)
      python3 gen_golden.py --check    (no write; exit 1 if the checked-in
      fixture differs from what this generator produces — drift detector;
      wired into `make pre-pr` via the verify-golden-vectors target)
"""
import argparse
import base64
import json
import os
import struct
import sys

import xxhash

SEED = 1337


def content_hash(tokens):
    buf = b"".join(struct.pack("<I", t & 0xFFFFFFFF) for t in tokens)
    return xxhash.xxh3_64_intdigest(buf, seed=SEED)


def next_seq(prev, content):
    return xxhash.xxh3_64_intdigest(
        struct.pack("<Q", prev) + struct.pack("<Q", content), seed=SEED
    )


def chains(tokens, block_size, parent=None):
    """Return (content_hashes, prefix_hashes) over the full blocks of tokens."""
    n_full = (len(tokens) // block_size) * block_size
    chs = [content_hash(tokens[i:i + block_size]) for i in range(0, n_full, block_size)]
    phs, prev = [], parent
    for ch in chs:
        ph = ch if prev is None else next_seq(prev, ch)
        phs.append(ph)
        prev = ph
    return chs, phs


# Sanity: XXH3 streaming (what SMG uses) == one-shot (what Go/this use).
def content_streaming(tokens):
    h = xxhash.xxh3_64(seed=SEED)
    for t in tokens:
        h.update(struct.pack("<I", t & 0xFFFFFFFF))
    return h.intdigest()


def hash_obj(h):
    """One hash in both interchange forms: decimal uint64 + 8-byte BE base64."""
    return {"dec": str(h), "b64be": base64.b64encode(h.to_bytes(8, "big")).decode()}


def vector(name, description, tokens, block_size, parent=None):
    chs, phs = chains(tokens, block_size, parent)
    return {
        "name": name,
        "description": description,
        "tokens": list(tokens),
        "block_size": block_size,
        "parent_prefix": hash_obj(parent) if parent is not None else None,
        "content_hashes": [hash_obj(h) for h in chs],
        "prefix_hashes": [hash_obj(h) for h in phs],
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true",
        help="verify golden_vectors.json matches this generator (no write); exit 1 on drift",
    )
    args = ap.parse_args()

    for toks in ([1, 2, 3], list(range(16)), list(range(40))):
        assert content_hash(toks) == content_streaming(toks)

    fixture = {
        "_source": (
            "Canonical copy: github.com/cachebox-project/inference-cache "
            "pkg/fingerprint/testdata/golden_vectors.json. Generated by "
            "gen_golden.py — do not edit by hand; downstream copies must stay "
            "byte-identical."
        ),
        "scheme": {
            "algorithm": "XXH3-64",
            "seed": 1337,
            "token_encoding": "each token id as little-endian u32",
            "content_hash": "XXH3-64(seed) over concat(le_u32(token) for token in block)",
            "prefix_chain": (
                "prefix[0] = content[0] when no parent, else "
                "XXH3-64(seed) over le_u64(parent) ++ le_u64(content[0]); "
                "prefix[i] = XXH3-64(seed) over le_u64(prefix[i-1]) ++ le_u64(content[i])"
            ),
            "wire_encoding": "8-byte big-endian (b64be = base64 of those bytes)",
            "partial_blocks": "trailing tokens short of block_size are dropped",
        },
        "vectors": [
            vector(
                "single_full_block",
                "Exactly one full block: prefix_hash[0] == content_hash[0].",
                list(range(1, 17)), 16,
            ),
            vector(
                "partial_tail_dropped",
                "20 tokens at block_size 16: one full block, 4-token tail dropped.",
                list(range(100, 120)), 16,
            ),
            vector(
                "two_block_chain",
                "Two full blocks: prefix_hash[1] chains prefix_hash[0].",
                list(range(1, 33)), 16,
            ),
            vector(
                "multi_block_chain",
                "Four full blocks: the rolling positional chain across a long prefix.",
                list(range(64)), 16,
            ),
            vector(
                "parent_chain",
                "Explicit parent prefix (hasParent=true): block 0 chains from "
                "parent_prefix instead of starting fresh — the suffix-event case.",
                list(range(50, 82)), 16, parent=0xDEADBEEF,
            ),
            vector(
                "partial_only_no_blocks",
                "Fewer tokens than one block: no hashes at all.",
                list(range(10)), 16,
            ),
        ],
    }

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "golden_vectors.json")
    rendered = json.dumps(fixture, indent=2) + "\n"

    if args.check:
        try:
            with open(out) as f:
                on_disk = f.read()
        except FileNotFoundError:
            print(f"DRIFT: {out} does not exist", file=sys.stderr)
            sys.exit(1)
        if on_disk != rendered:
            print(
                f"DRIFT: {out} differs from what gen_golden.py produces — the "
                "frozen scheme or the fixture was changed unilaterally",
                file=sys.stderr,
            )
            sys.exit(1)
        print("golden_vectors.json is current (regeneration is a no-op)")
        return

    with open(out, "w") as f:
        f.write(rendered)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
