resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- cachebackend_editor_role.yaml
- cachebackend_viewer_role.yaml
- cacheindex_editor_role.yaml
- cacheindex_viewer_role.yaml
- cachepolicy_editor_role.yaml
- cachepolicy_viewer_role.yaml
- cachetenant_editor_role.yaml
- cachetenant_viewer_role.yaml
- pdtopology_editor_role.yaml
- pdtopology_viewer_role.yaml
- prompttemplate_editor_role.yaml
- prompttemplate_viewer_role.yaml
