package fingerprint

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

// The golden values live in testdata/golden_vectors.json — the canonical,
// language-neutral fixture for the content-fingerprint scheme, generated by
// testdata/gen_golden.py from an independent implementation (Python `xxhash`).
// The same fixture is asserted by the inference-cache-benchmark proxy (Python)
// and SMG's event_tree (Rust), so a unilateral change to the construction in
// any implementation fails loudly in all of them.

type goldenHash struct {
	Dec   string `json:"dec"`
	B64BE string `json:"b64be"`
}

type goldenVector struct {
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	Tokens        []uint32     `json:"tokens"`
	BlockSize     int          `json:"block_size"`
	ParentPrefix  *goldenHash  `json:"parent_prefix"`
	ContentHashes []goldenHash `json:"content_hashes"`
	PrefixHashes  []goldenHash `json:"prefix_hashes"`
}

type goldenFile struct {
	Vectors []goldenVector `json:"vectors"`
}

func loadGoldenVectors(t *testing.T) []goldenVector {
	t.Helper()
	raw, err := os.ReadFile("testdata/golden_vectors.json")
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}
	var f goldenFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse golden fixture: %v", err)
	}
	if len(f.Vectors) == 0 {
		t.Fatal("golden fixture has no vectors")
	}
	return f.Vectors
}

// value parses the decimal form and cross-checks the base64 8-byte big-endian
// wire form against it, so the fixture itself can't carry an inconsistent pair.
func (g goldenHash) value(t *testing.T, ctx string) uint64 {
	t.Helper()
	h, err := strconv.ParseUint(g.Dec, 10, 64)
	if err != nil {
		t.Fatalf("%s: bad dec %q: %v", ctx, g.Dec, err)
	}
	wire, err := base64.StdEncoding.DecodeString(g.B64BE)
	if err != nil {
		t.Fatalf("%s: bad b64be %q: %v", ctx, g.B64BE, err)
	}
	if len(wire) != 8 {
		t.Fatalf("%s: b64be decodes to %d bytes, want 8", ctx, len(wire))
	}
	if got := string(Bytes(h)); got != string(wire) {
		t.Fatalf("%s: b64be bytes %x disagree with dec %s (Bytes() = %x)", ctx, wire, g.Dec, Bytes(h))
	}
	return h
}

func TestGoldenVectors(t *testing.T) {
	for _, v := range loadGoldenVectors(t) {
		t.Run(v.Name, func(t *testing.T) {
			// Content hashes: position-independent, per full block.
			nFull := 0
			if v.BlockSize > 0 {
				nFull = len(v.Tokens) / v.BlockSize
			}
			if len(v.ContentHashes) != nFull {
				t.Fatalf("fixture has %d content_hashes, want %d full blocks", len(v.ContentHashes), nFull)
			}
			for i, want := range v.ContentHashes {
				block := v.Tokens[i*v.BlockSize : (i+1)*v.BlockSize]
				if got, w := ContentHash(block), want.value(t, "content"); got != w {
					t.Errorf("ContentHash(block %d) = %d, want %d", i, got, w)
				}
			}

			// Prefix hashes: rolling positional chain, optionally from a parent.
			var got []uint64
			if v.ParentPrefix != nil {
				got = PrefixHashesFrom(v.Tokens, v.BlockSize, v.ParentPrefix.value(t, "parent"), true)
			} else {
				got = PrefixHashes(v.Tokens, v.BlockSize)
			}
			if len(got) != len(v.PrefixHashes) {
				t.Fatalf("got %d prefix hashes, want %d", len(got), len(v.PrefixHashes))
			}
			for i, want := range v.PrefixHashes {
				if w := want.value(t, "prefix"); got[i] != w {
					t.Errorf("prefix_hash[%d] = %d, want %d", i, got[i], w)
				}
			}
		})
	}
}

// The scheme is frozen: these hardcoded anchors exist so that regenerating the
// fixture under a silently-changed construction (which would keep
// TestGoldenVectors green by construction) still fails here. They pin every
// layer of the scheme — per-block content hashing, the LE-u64 rolling chain,
// and the explicit-parent chain. Do not update them without coordinating every
// producer and consumer of these hashes.
func TestSchemeFrozenAnchor(t *testing.T) {
	if got := ContentHash(seq(1, 16)); got != 16863443419780771464 {
		t.Fatalf("ContentHash(seq(1,16)) = %d, want 16863443419780771464 — the frozen scheme changed", got)
	}
	if got := PrefixHashes(seq(0, 64), 16)[3]; got != 3888788807566526800 {
		t.Fatalf("PrefixHashes(seq(0,64),16)[3] = %d, want 3888788807566526800 — the rolling chain changed", got)
	}
	if got := PrefixHashesFrom(seq(50, 32), 16, 0xDEADBEEF, true)[1]; got != 2998384554010166533 {
		t.Fatalf("PrefixHashesFrom(seq(50,32),16,0xDEADBEEF,true)[1] = %d, want 2998384554010166533 — parent chaining changed", got)
	}
}

// prefix_hash[0] must equal content_hash[0] (fresh sequence, no parent).
func TestPrefixZeroEqualsContent(t *testing.T) {
	toks := seq(7, 16)
	if PrefixHashes(toks, 16)[0] != ContentHash(toks) {
		t.Fatal("prefix_hash[0] != content_hash[0]")
	}
}

// A parent chain must make block 0 differ from the fresh case (positionality).
func TestParentChainShiftsHash(t *testing.T) {
	toks := seq(50, 16)
	fresh := PrefixHashes(toks, 16)[0]
	chained := PrefixHashesFrom(toks, 16, 0xDEADBEEF, true)[0]
	if fresh == chained {
		t.Fatal("parent chaining did not change block-0 hash; positionality broken")
	}
}

// Degenerate inputs return nil. blockSize <= 0 is Go-specific guard behavior
// (the cross-language fixture only carries block_size > 0 vectors).
func TestDegenerateInputsReturnNil(t *testing.T) {
	if got := PrefixHashes(seq(0, 32), 0); got != nil {
		t.Errorf("blockSize 0: got %v, want nil", got)
	}
	if got := PrefixHashes(seq(0, 32), -1); got != nil {
		t.Errorf("blockSize -1: got %v, want nil", got)
	}
	if got := PrefixHashes(nil, 16); got != nil {
		t.Errorf("no tokens: got %v, want nil", got)
	}
}

// seq returns [start, start+1, ..., start+n-1] as uint32.
func seq(start, n int) []uint32 {
	out := make([]uint32, n)
	for i := range out {
		out[i] = uint32(start + i)
	}
	return out
}
