apiVersion: inferencecache.io/v1alpha1
kind: CacheBackend
metadata:
  labels:
    app.kubernetes.io/name: inference-cache
    app.kubernetes.io/managed-by: kustomize
  name: cachebackend-sample
spec:
  type: LMCache
  deploymentKind: StatefulSet
  replicas: 1
  storage:
    pvc:
      size: 10Gi
  integration:
    engine: SGLang
    role: ReadWrite
  engineSelector:
    matchLabels:
      inferencecache.io/cache-enabled: "true"
  backendConfig:
    evictionPolicy: LRU
