//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackend) DeepCopyInto(out *CacheBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackend.
func (in *CacheBackend) DeepCopy() *CacheBackend {
	if in == nil {
		return nil
	}
	out := new(CacheBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendAutoscalingSpec) DeepCopyInto(out *CacheBackendAutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercent != nil {
		in, out := &in.TargetCPUUtilizationPercent, &out.TargetCPUUtilizationPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendAutoscalingSpec.
func (in *CacheBackendAutoscalingSpec) DeepCopy() *CacheBackendAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(CacheBackendAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendEngineSelector) DeepCopyInto(out *CacheBackendEngineSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendEngineSelector.
func (in *CacheBackendEngineSelector) DeepCopy() *CacheBackendEngineSelector {
	if in == nil {
		return nil
	}
	out := new(CacheBackendEngineSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendIndexParticipation) DeepCopyInto(out *CacheBackendIndexParticipation) {
	*out = *in
	if in.LastEventAt != nil {
		in, out := &in.LastEventAt, &out.LastEventAt
		*out = (*in).DeepCopy()
	}
	if in.HitRate != nil {
		in, out := &in.HitRate, &out.HitRate
		*out = new(string)
		**out = **in
	}
	if in.T2HitRate != nil {
		in, out := &in.T2HitRate, &out.T2HitRate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendIndexParticipation.
func (in *CacheBackendIndexParticipation) DeepCopy() *CacheBackendIndexParticipation {
	if in == nil {
		return nil
	}
	out := new(CacheBackendIndexParticipation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendIntegrationSpec) DeepCopyInto(out *CacheBackendIntegrationSpec) {
	*out = *in
	if in.FirstEventTimeout != nil {
		in, out := &in.FirstEventTimeout, &out.FirstEventTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	if in.EngineOverrides != nil {
		in, out := &in.EngineOverrides, &out.EngineOverrides
		*out = new(EngineInjectionOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendIntegrationSpec.
func (in *CacheBackendIntegrationSpec) DeepCopy() *CacheBackendIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(CacheBackendIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendList) DeepCopyInto(out *CacheBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendList.
func (in *CacheBackendList) DeepCopy() *CacheBackendList {
	if in == nil {
		return nil
	}
	out := new(CacheBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendPodSpecOverride) DeepCopyInto(out *CacheBackendPodSpecOverride) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendPodSpecOverride.
func (in *CacheBackendPodSpecOverride) DeepCopy() *CacheBackendPodSpecOverride {
	if in == nil {
		return nil
	}
	out := new(CacheBackendPodSpecOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendSpec) DeepCopyInto(out *CacheBackendSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(CacheBackendAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Integration != nil {
		in, out := &in.Integration, &out.Integration
		*out = new(CacheBackendIntegrationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EngineSelector != nil {
		in, out := &in.EngineSelector, &out.EngineSelector
		*out = new(CacheBackendEngineSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendConfig != nil {
		in, out := &in.BackendConfig, &out.BackendConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(CacheBackendPodSpecOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendSpec.
func (in *CacheBackendSpec) DeepCopy() *CacheBackendSpec {
	if in == nil {
		return nil
	}
	out := new(CacheBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheBackendStatus) DeepCopyInto(out *CacheBackendStatus) {
	*out = *in
	if in.MatchedEnginePods != nil {
		in, out := &in.MatchedEnginePods, &out.MatchedEnginePods
		*out = new(int32)
		**out = **in
	}
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	if in.FirstKVEventObservedAt != nil {
		in, out := &in.FirstKVEventObservedAt, &out.FirstKVEventObservedAt
		*out = (*in).DeepCopy()
	}
	if in.FirstAvailableAt != nil {
		in, out := &in.FirstAvailableAt, &out.FirstAvailableAt
		*out = (*in).DeepCopy()
	}
	if in.IndexParticipation != nil {
		in, out := &in.IndexParticipation, &out.IndexParticipation
		*out = new(CacheBackendIndexParticipation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheBackendStatus.
func (in *CacheBackendStatus) DeepCopy() *CacheBackendStatus {
	if in == nil {
		return nil
	}
	out := new(CacheBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheIndex) DeepCopyInto(out *CacheIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheIndex.
func (in *CacheIndex) DeepCopy() *CacheIndex {
	if in == nil {
		return nil
	}
	out := new(CacheIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheIndexList) DeepCopyInto(out *CacheIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheIndexList.
func (in *CacheIndexList) DeepCopy() *CacheIndexList {
	if in == nil {
		return nil
	}
	out := new(CacheIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheIndexSpec) DeepCopyInto(out *CacheIndexSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheIndexSpec.
func (in *CacheIndexSpec) DeepCopy() *CacheIndexSpec {
	if in == nil {
		return nil
	}
	out := new(CacheIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheIndexStatus) DeepCopyInto(out *CacheIndexStatus) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]ReplicaCacheStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tenants != nil {
		in, out := &in.Tenants, &out.Tenants
		*out = make([]TenantCacheStatus, len(*in))
		copy(*out, *in)
	}
	out.Prefixes = in.Prefixes
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheIndexStatus.
func (in *CacheIndexStatus) DeepCopy() *CacheIndexStatus {
	if in == nil {
		return nil
	}
	out := new(CacheIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePolicy) DeepCopyInto(out *CachePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePolicy.
func (in *CachePolicy) DeepCopy() *CachePolicy {
	if in == nil {
		return nil
	}
	out := new(CachePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePolicyList) DeepCopyInto(out *CachePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CachePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePolicyList.
func (in *CachePolicyList) DeepCopy() *CachePolicyList {
	if in == nil {
		return nil
	}
	out := new(CachePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePolicySpec) DeepCopyInto(out *CachePolicySpec) {
	*out = *in
	if in.EvictionTTL != nil {
		in, out := &in.EvictionTTL, &out.EvictionTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MinimumPrefixTokens != nil {
		in, out := &in.MinimumPrefixTokens, &out.MinimumPrefixTokens
		*out = new(int32)
		**out = **in
	}
	if in.MinimumMatchedTokens != nil {
		in, out := &in.MinimumMatchedTokens, &out.MinimumMatchedTokens
		*out = new(int32)
		**out = **in
	}
	if in.RoutingFloorScore != nil {
		in, out := &in.RoutingFloorScore, &out.RoutingFloorScore
		*out = new(string)
		**out = **in
	}
	if in.LookupTimeoutMs != nil {
		in, out := &in.LookupTimeoutMs, &out.LookupTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(CachePolicyStrategySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePolicySpec.
func (in *CachePolicySpec) DeepCopy() *CachePolicySpec {
	if in == nil {
		return nil
	}
	out := new(CachePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePolicyStatus) DeepCopyInto(out *CachePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePolicyStatus.
func (in *CachePolicyStatus) DeepCopy() *CachePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CachePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachePolicyStrategySpec) DeepCopyInto(out *CachePolicyStrategySpec) {
	*out = *in
	if in.EnableChainMatching != nil {
		in, out := &in.EnableChainMatching, &out.EnableChainMatching
		*out = new(bool)
		**out = **in
	}
	if in.RequireChain != nil {
		in, out := &in.RequireChain, &out.RequireChain
		*out = new(bool)
		**out = **in
	}
	if in.EnableTenantHot != nil {
		in, out := &in.EnableTenantHot, &out.EnableTenantHot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachePolicyStrategySpec.
func (in *CachePolicyStrategySpec) DeepCopy() *CachePolicyStrategySpec {
	if in == nil {
		return nil
	}
	out := new(CachePolicyStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenant) DeepCopyInto(out *CacheTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenant.
func (in *CacheTenant) DeepCopy() *CacheTenant {
	if in == nil {
		return nil
	}
	out := new(CacheTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenantCryptoSpec) DeepCopyInto(out *CacheTenantCryptoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenantCryptoSpec.
func (in *CacheTenantCryptoSpec) DeepCopy() *CacheTenantCryptoSpec {
	if in == nil {
		return nil
	}
	out := new(CacheTenantCryptoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenantList) DeepCopyInto(out *CacheTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenantList.
func (in *CacheTenantList) DeepCopy() *CacheTenantList {
	if in == nil {
		return nil
	}
	out := new(CacheTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenantQuotaSpec) DeepCopyInto(out *CacheTenantQuotaSpec) {
	*out = *in
	if in.MaxIndexEntries != nil {
		in, out := &in.MaxIndexEntries, &out.MaxIndexEntries
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenantQuotaSpec.
func (in *CacheTenantQuotaSpec) DeepCopy() *CacheTenantQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(CacheTenantQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenantSpec) DeepCopyInto(out *CacheTenantSpec) {
	*out = *in
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(CacheTenantQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Crypto != nil {
		in, out := &in.Crypto, &out.Crypto
		*out = new(CacheTenantCryptoSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenantSpec.
func (in *CacheTenantSpec) DeepCopy() *CacheTenantSpec {
	if in == nil {
		return nil
	}
	out := new(CacheTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheTenantStatus) DeepCopyInto(out *CacheTenantStatus) {
	*out = *in
	if in.IndexEntries != nil {
		in, out := &in.IndexEntries, &out.IndexEntries
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheTenantStatus.
func (in *CacheTenantStatus) DeepCopy() *CacheTenantStatus {
	if in == nil {
		return nil
	}
	out := new(CacheTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineInjectionOverrides) DeepCopyInto(out *EngineInjectionOverrides) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SuppressArgs != nil {
		in, out := &in.SuppressArgs, &out.SuppressArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuppressEnv != nil {
		in, out := &in.SuppressEnv, &out.SuppressEnv
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineInjectionOverrides.
func (in *EngineInjectionOverrides) DeepCopy() *EngineInjectionOverrides {
	if in == nil {
		return nil
	}
	out := new(EngineInjectionOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDAcceleratorTypeSpec) DeepCopyInto(out *PDAcceleratorTypeSpec) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDAcceleratorTypeSpec.
func (in *PDAcceleratorTypeSpec) DeepCopy() *PDAcceleratorTypeSpec {
	if in == nil {
		return nil
	}
	out := new(PDAcceleratorTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDPoolSpec) DeepCopyInto(out *PDPoolSpec) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDPoolSpec.
func (in *PDPoolSpec) DeepCopy() *PDPoolSpec {
	if in == nil {
		return nil
	}
	out := new(PDPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDTopology) DeepCopyInto(out *PDTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDTopology.
func (in *PDTopology) DeepCopy() *PDTopology {
	if in == nil {
		return nil
	}
	out := new(PDTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDTopologyList) DeepCopyInto(out *PDTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PDTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDTopologyList.
func (in *PDTopologyList) DeepCopy() *PDTopologyList {
	if in == nil {
		return nil
	}
	out := new(PDTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDTopologySpec) DeepCopyInto(out *PDTopologySpec) {
	*out = *in
	if in.PrefillPools != nil {
		in, out := &in.PrefillPools, &out.PrefillPools
		*out = make([]PDPoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DecodePools != nil {
		in, out := &in.DecodePools, &out.DecodePools
		*out = make([]PDPoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcceleratorTypes != nil {
		in, out := &in.AcceleratorTypes, &out.AcceleratorTypes
		*out = make([]PDAcceleratorTypeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDTopologySpec.
func (in *PDTopologySpec) DeepCopy() *PDTopologySpec {
	if in == nil {
		return nil
	}
	out := new(PDTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDTopologyStatus) DeepCopyInto(out *PDTopologyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDTopologyStatus.
func (in *PDTopologyStatus) DeepCopy() *PDTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(PDTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixStatus) DeepCopyInto(out *PrefixStatus) {
	*out = *in
	out.Summary = in.Summary
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixStatus.
func (in *PrefixStatus) DeepCopy() *PrefixStatus {
	if in == nil {
		return nil
	}
	out := new(PrefixStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixSummary) DeepCopyInto(out *PrefixSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixSummary.
func (in *PrefixSummary) DeepCopy() *PrefixSummary {
	if in == nil {
		return nil
	}
	out := new(PrefixSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplate) DeepCopyInto(out *PromptTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplate.
func (in *PromptTemplate) DeepCopy() *PromptTemplate {
	if in == nil {
		return nil
	}
	out := new(PromptTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromptTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateList) DeepCopyInto(out *PromptTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromptTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateList.
func (in *PromptTemplateList) DeepCopy() *PromptTemplateList {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromptTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateSlot) DeepCopyInto(out *PromptTemplateSlot) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateSlot.
func (in *PromptTemplateSlot) DeepCopy() *PromptTemplateSlot {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateSpec) DeepCopyInto(out *PromptTemplateSpec) {
	*out = *in
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = make([]PromptTemplateSlot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateSpec.
func (in *PromptTemplateSpec) DeepCopy() *PromptTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptTemplateStatus) DeepCopyInto(out *PromptTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptTemplateStatus.
func (in *PromptTemplateStatus) DeepCopy() *PromptTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaCacheStatus) DeepCopyInto(out *ReplicaCacheStatus) {
	*out = *in
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaCacheStatus.
func (in *ReplicaCacheStatus) DeepCopy() *ReplicaCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCacheStatus) DeepCopyInto(out *TenantCacheStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCacheStatus.
func (in *TenantCacheStatus) DeepCopy() *TenantCacheStatus {
	if in == nil {
		return nil
	}
	out := new(TenantCacheStatus)
	in.DeepCopyInto(out)
	return out
}
