// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: inferencecache/v1alpha1/inferencecache.proto

package inferencecachev1alpha1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceCache_RenderTemplate_FullMethodName    = "/inferencecache.v1alpha1.InferenceCache/RenderTemplate"
	InferenceCache_LookupRoute_FullMethodName       = "/inferencecache.v1alpha1.InferenceCache/LookupRoute"
	InferenceCache_LookupPDRoute_FullMethodName     = "/inferencecache.v1alpha1.InferenceCache/LookupPDRoute"
	InferenceCache_GetCacheState_FullMethodName     = "/inferencecache.v1alpha1.InferenceCache/GetCacheState"
	InferenceCache_ReportCacheState_FullMethodName  = "/inferencecache.v1alpha1.InferenceCache/ReportCacheState"
	InferenceCache_PublishEvent_FullMethodName      = "/inferencecache.v1alpha1.InferenceCache/PublishEvent"
	InferenceCache_StreamCacheEvents_FullMethodName = "/inferencecache.v1alpha1.InferenceCache/StreamCacheEvents"
	InferenceCache_StreamMetrics_FullMethodName     = "/inferencecache.v1alpha1.InferenceCache/StreamMetrics"
)

// InferenceCacheClient is the client API for InferenceCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceCache is the cache-policy control-plane API. See
// docs/design/grpc-contract.md.
//
// Guarantees:
//   - RenderTemplate / LookupRoute / LookupPDRoute / GetCacheState are
//     side-effect-free apart from emitting metrics.
//   - Fail-open: an empty result with reason_code NO_HINT is valid; clients
//     treat it as a no-op and route as they normally would.
//   - prefix_hash and block_hashes bytes are engine-defined and only matched
//     within a matching hash_scheme; the server never interprets them.
//   - RenderTemplate is deterministic for a fixed
//     (template_ref, variables, template_revision).
//   - CacheStateUpdate / PrefixEntry carry metadata only — never KV tensors or
//     prompt text.
type InferenceCacheClient interface {
	// Consumer side (gateways).
	RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error)
	LookupRoute(ctx context.Context, in *LookupRouteRequest, opts ...grpc.CallOption) (*LookupRouteResponse, error)
	LookupPDRoute(ctx context.Context, in *LookupPDRouteRequest, opts ...grpc.CallOption) (*LookupPDRouteResponse, error)
	GetCacheState(ctx context.Context, in *GetCacheStateRequest, opts ...grpc.CallOption) (*GetCacheStateResponse, error)
	// Producer side (engine adapters).
	ReportCacheState(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CacheStateUpdate, Ack], error)
	PublishEvent(ctx context.Context, in *CacheEvent, opts ...grpc.CallOption) (*Ack, error)
	// Observer side (dashboards, debug tooling).
	StreamCacheEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CacheEvent], error)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metric], error)
}

type inferenceCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceCacheClient(cc grpc.ClientConnInterface) InferenceCacheClient {
	return &inferenceCacheClient{cc}
}

func (c *inferenceCacheClient) RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderTemplateResponse)
	err := c.cc.Invoke(ctx, InferenceCache_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceCacheClient) LookupRoute(ctx context.Context, in *LookupRouteRequest, opts ...grpc.CallOption) (*LookupRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupRouteResponse)
	err := c.cc.Invoke(ctx, InferenceCache_LookupRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceCacheClient) LookupPDRoute(ctx context.Context, in *LookupPDRouteRequest, opts ...grpc.CallOption) (*LookupPDRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupPDRouteResponse)
	err := c.cc.Invoke(ctx, InferenceCache_LookupPDRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceCacheClient) GetCacheState(ctx context.Context, in *GetCacheStateRequest, opts ...grpc.CallOption) (*GetCacheStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCacheStateResponse)
	err := c.cc.Invoke(ctx, InferenceCache_GetCacheState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceCacheClient) ReportCacheState(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CacheStateUpdate, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceCache_ServiceDesc.Streams[0], InferenceCache_ReportCacheState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CacheStateUpdate, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_ReportCacheStateClient = grpc.ClientStreamingClient[CacheStateUpdate, Ack]

func (c *inferenceCacheClient) PublishEvent(ctx context.Context, in *CacheEvent, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, InferenceCache_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceCacheClient) StreamCacheEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CacheEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceCache_ServiceDesc.Streams[1], InferenceCache_StreamCacheEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, CacheEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_StreamCacheEventsClient = grpc.ServerStreamingClient[CacheEvent]

func (c *inferenceCacheClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceCache_ServiceDesc.Streams[2], InferenceCache_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, Metric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_StreamMetricsClient = grpc.ServerStreamingClient[Metric]

// InferenceCacheServer is the server API for InferenceCache service.
// All implementations must embed UnimplementedInferenceCacheServer
// for forward compatibility.
//
// InferenceCache is the cache-policy control-plane API. See
// docs/design/grpc-contract.md.
//
// Guarantees:
//   - RenderTemplate / LookupRoute / LookupPDRoute / GetCacheState are
//     side-effect-free apart from emitting metrics.
//   - Fail-open: an empty result with reason_code NO_HINT is valid; clients
//     treat it as a no-op and route as they normally would.
//   - prefix_hash and block_hashes bytes are engine-defined and only matched
//     within a matching hash_scheme; the server never interprets them.
//   - RenderTemplate is deterministic for a fixed
//     (template_ref, variables, template_revision).
//   - CacheStateUpdate / PrefixEntry carry metadata only — never KV tensors or
//     prompt text.
type InferenceCacheServer interface {
	// Consumer side (gateways).
	RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error)
	LookupRoute(context.Context, *LookupRouteRequest) (*LookupRouteResponse, error)
	LookupPDRoute(context.Context, *LookupPDRouteRequest) (*LookupPDRouteResponse, error)
	GetCacheState(context.Context, *GetCacheStateRequest) (*GetCacheStateResponse, error)
	// Producer side (engine adapters).
	ReportCacheState(grpc.ClientStreamingServer[CacheStateUpdate, Ack]) error
	PublishEvent(context.Context, *CacheEvent) (*Ack, error)
	// Observer side (dashboards, debug tooling).
	StreamCacheEvents(*StreamEventsRequest, grpc.ServerStreamingServer[CacheEvent]) error
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[Metric]) error
	mustEmbedUnimplementedInferenceCacheServer()
}

// UnimplementedInferenceCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceCacheServer struct{}

func (UnimplementedInferenceCacheServer) RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedInferenceCacheServer) LookupRoute(context.Context, *LookupRouteRequest) (*LookupRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupRoute not implemented")
}
func (UnimplementedInferenceCacheServer) LookupPDRoute(context.Context, *LookupPDRouteRequest) (*LookupPDRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupPDRoute not implemented")
}
func (UnimplementedInferenceCacheServer) GetCacheState(context.Context, *GetCacheStateRequest) (*GetCacheStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCacheState not implemented")
}
func (UnimplementedInferenceCacheServer) ReportCacheState(grpc.ClientStreamingServer[CacheStateUpdate, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method ReportCacheState not implemented")
}
func (UnimplementedInferenceCacheServer) PublishEvent(context.Context, *CacheEvent) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedInferenceCacheServer) StreamCacheEvents(*StreamEventsRequest, grpc.ServerStreamingServer[CacheEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCacheEvents not implemented")
}
func (UnimplementedInferenceCacheServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[Metric]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedInferenceCacheServer) mustEmbedUnimplementedInferenceCacheServer() {}
func (UnimplementedInferenceCacheServer) testEmbeddedByValue()                        {}

// UnsafeInferenceCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceCacheServer will
// result in compilation errors.
type UnsafeInferenceCacheServer interface {
	mustEmbedUnimplementedInferenceCacheServer()
}

func RegisterInferenceCacheServer(s grpc.ServiceRegistrar, srv InferenceCacheServer) {
	// If the following call pancis, it indicates UnimplementedInferenceCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceCache_ServiceDesc, srv)
}

func _InferenceCache_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceCacheServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceCache_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceCacheServer).RenderTemplate(ctx, req.(*RenderTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceCache_LookupRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceCacheServer).LookupRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceCache_LookupRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceCacheServer).LookupRoute(ctx, req.(*LookupRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceCache_LookupPDRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPDRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceCacheServer).LookupPDRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceCache_LookupPDRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceCacheServer).LookupPDRoute(ctx, req.(*LookupPDRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceCache_GetCacheState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceCacheServer).GetCacheState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceCache_GetCacheState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceCacheServer).GetCacheState(ctx, req.(*GetCacheStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceCache_ReportCacheState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceCacheServer).ReportCacheState(&grpc.GenericServerStream[CacheStateUpdate, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_ReportCacheStateServer = grpc.ClientStreamingServer[CacheStateUpdate, Ack]

func _InferenceCache_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceCacheServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceCache_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceCacheServer).PublishEvent(ctx, req.(*CacheEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceCache_StreamCacheEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceCacheServer).StreamCacheEvents(m, &grpc.GenericServerStream[StreamEventsRequest, CacheEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_StreamCacheEventsServer = grpc.ServerStreamingServer[CacheEvent]

func _InferenceCache_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceCacheServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, Metric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceCache_StreamMetricsServer = grpc.ServerStreamingServer[Metric]

// InferenceCache_ServiceDesc is the grpc.ServiceDesc for InferenceCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inferencecache.v1alpha1.InferenceCache",
	HandlerType: (*InferenceCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderTemplate",
			Handler:    _InferenceCache_RenderTemplate_Handler,
		},
		{
			MethodName: "LookupRoute",
			Handler:    _InferenceCache_LookupRoute_Handler,
		},
		{
			MethodName: "LookupPDRoute",
			Handler:    _InferenceCache_LookupPDRoute_Handler,
		},
		{
			MethodName: "GetCacheState",
			Handler:    _InferenceCache_GetCacheState_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _InferenceCache_PublishEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportCacheState",
			Handler:       _InferenceCache_ReportCacheState_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamCacheEvents",
			Handler:       _InferenceCache_StreamCacheEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _InferenceCache_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inferencecache/v1alpha1/inferencecache.proto",
}
