// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: vllm_engine.proto

// Minimal vendored subset of the SMG vLLM engine gRPC contract
// (machxai/smg: crates/grpc_client/proto/vllm_engine.proto) — ONLY the GetLoads
// RPC and its messages. The kvevent-subscriber uses this to read engine load
// over gRPC as an alternative to scraping HTTP /metrics (which an SMG gRPC
// engine does not expose).
//
// The package name MUST stay `vllm.grpc.engine` to match the upstream service
// so the wire method path `/vllm.grpc.engine.VllmEngine/GetLoads` lines up; the
// message names, field numbers, and types below are copied verbatim from the
// source file so the wire encoding is byte-compatible. Kept out of the `proto/`
// module on purpose — it is a vendored external contract, not part of IC's own
// gRPC API, so it is exempt from IC's buf-lint conventions.
//
// Provenance: vendored from machxai/smg crates/grpc_client/proto/vllm_engine.proto
// at commit 6d63ec83f052af42649a330d91f39aa56471aceb (2026-07-09). The GetLoads
// RPC and the GetLoadsRequest / GetLoadsResponse / SchedulerLoad messages below
// were verified field-for-field (numbers and types) against that revision. When
// re-syncing against a newer SMG release, re-copy from the pinned commit, update
// this line, and re-verify the field numbers. The bufconn test
// (grpc_loads_scraper_test.go) only proves this file round-trips against its own
// generated stubs — NOT that it matches the engine actually deployed.
//
// Regenerate the .pb.go stubs with `make proto-gen-vendored` (also run by `make
// proto-gen`); CI diffs pkg/adapters/engine/vllmengine to catch drift, so the
// two committed stubs stay reproducible from this file.

package vllmengine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VllmEngine_GetLoads_FullMethodName = "/vllm.grpc.engine.VllmEngine/GetLoads"
)

// VllmEngineClient is the client API for VllmEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VllmEngineClient interface {
	// Scheduler load metrics, per DP rank.
	GetLoads(ctx context.Context, in *GetLoadsRequest, opts ...grpc.CallOption) (*GetLoadsResponse, error)
}

type vllmEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewVllmEngineClient(cc grpc.ClientConnInterface) VllmEngineClient {
	return &vllmEngineClient{cc}
}

func (c *vllmEngineClient) GetLoads(ctx context.Context, in *GetLoadsRequest, opts ...grpc.CallOption) (*GetLoadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadsResponse)
	err := c.cc.Invoke(ctx, VllmEngine_GetLoads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VllmEngineServer is the server API for VllmEngine service.
// All implementations must embed UnimplementedVllmEngineServer
// for forward compatibility.
type VllmEngineServer interface {
	// Scheduler load metrics, per DP rank.
	GetLoads(context.Context, *GetLoadsRequest) (*GetLoadsResponse, error)
	mustEmbedUnimplementedVllmEngineServer()
}

// UnimplementedVllmEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVllmEngineServer struct{}

func (UnimplementedVllmEngineServer) GetLoads(context.Context, *GetLoadsRequest) (*GetLoadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoads not implemented")
}
func (UnimplementedVllmEngineServer) mustEmbedUnimplementedVllmEngineServer() {}
func (UnimplementedVllmEngineServer) testEmbeddedByValue()                    {}

// UnsafeVllmEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VllmEngineServer will
// result in compilation errors.
type UnsafeVllmEngineServer interface {
	mustEmbedUnimplementedVllmEngineServer()
}

func RegisterVllmEngineServer(s grpc.ServiceRegistrar, srv VllmEngineServer) {
	// If the following call pancis, it indicates UnimplementedVllmEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VllmEngine_ServiceDesc, srv)
}

func _VllmEngine_GetLoads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).GetLoads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_GetLoads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).GetLoads(ctx, req.(*GetLoadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VllmEngine_ServiceDesc is the grpc.ServiceDesc for VllmEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VllmEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vllm.grpc.engine.VllmEngine",
	HandlerType: (*VllmEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoads",
			Handler:    _VllmEngine_GetLoads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vllm_engine.proto",
}
